<a href="https://colab.research.google.com/github/priyanshgupta1998/Machine_learning/blob/master/Extract_Car_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# WebScraping

In [0]:
# import pandas as pd
# import numpy as np
# # Reading an excel file using Python 
# import xlrd 
# # Give the location of the file 
# loc = ("Used_Car_Data_Alto.xlsx") 

# # To open Workbook 
# wb = xlrd.open_workbook(loc) 
# # xl_file= pd.ExcelFile("Used_Car_Data_Alto.xlsx")
# # xl_file
# sheet = wb.sheet_by_index(1) 


# dat = []
# sheet = wb.sheet_by_index(1)

# # # For row 0 and column 0 
# # sheet.cell_value(1,2) 
# for i in range(sheet.nrows): 
#     liss=[]
#     for j in range(sheet.ncols):
#         liss.append(sheet.cell_value(i, j)) 
#     dat.append(liss)

In [0]:
data = pd.DataFrame(dat[1:] , columns = dat[0])
print(data.shape)
data.head()

(24, 12)

,S.no,Car,Brand,Model,Variant,Fuel Type,Model Year,Mileage,Price,City,Site,Url
0,1.0,Maruti Suzuki Alto LX BS-IV,Maruti Suzuki,Alto,LX,Petrol,2012.0,"7,000 Km",138000.0,Hissar,Droom,https://droom.in/product/maruti-suzuki-alto-lx...
1,2.0,Maruti Suzuki Alto LXi BS-III,Maruti Suzuki,Alto,LXI,Petrol,2011.0,"4,000 Km",141000.0,Hissar,Droom,https://droom.in/product/maruti-suzuki-alto-lx...
2,3.0,Maruti Suzuki Alto K10 VXi,Maruti Suzuki,K10,VXI,Petrol,2012.0,"89,000 Km",145700.0,Faridabad,Droom,https://droom.in/product/maruti-suzuki-alto-k1...
3,4.0,Maruti Suzuki ALTO 800 LXi,Maruti Suzuki,800,LXI,Petrol,2013.0,"35,000 Km",150000.0,Delhi,Droom,https://droom.in/product/maruti-suzuki-alto-80...
4,5.0,Maruti Suzuki ALTO 800 LXi,Maruti Suzuki,800,LXI,Petrol,2012.0,"35,000 Km",130000.0,Delhi,Droom,https://droom.in/product/maruti-suzuki-alto-80...

In [0]:
data.drop(['S.no'] , axis=1 , inplace=True)
print(data.shape)

(24, 11)

In [0]:
data.head()

,Car,Brand,Model,Variant,Fuel Type,Model Year,Mileage,Price,City,Site,Url
0,Maruti Suzuki Alto LX BS-IV,Maruti Suzuki,Alto,LX,Petrol,2012.0,"7,000 Km",138000.0,Hissar,Droom,https://droom.in/product/maruti-suzuki-alto-lx...
1,Maruti Suzuki Alto LXi BS-III,Maruti Suzuki,Alto,LXI,Petrol,2011.0,"4,000 Km",141000.0,Hissar,Droom,https://droom.in/product/maruti-suzuki-alto-lx...
2,Maruti Suzuki Alto K10 VXi,Maruti Suzuki,K10,VXI,Petrol,2012.0,"89,000 Km",145700.0,Faridabad,Droom,https://droom.in/product/maruti-suzuki-alto-k1...
3,Maruti Suzuki ALTO 800 LXi,Maruti Suzuki,800,LXI,Petrol,2013.0,"35,000 Km",150000.0,Delhi,Droom,https://droom.in/product/maruti-suzuki-alto-80...
4,Maruti Suzuki ALTO 800 LXi,Maruti Suzuki,800,LXI,Petrol,2012.0,"35,000 Km",130000.0,Delhi,Droom,https://droom.in/product/maruti-suzuki-alto-80...

In [0]:
data.columns

Index(['Car', 'Brand', 'Model', 'Variant', 'Fuel Type', 'Model Year',
       'Mileage', 'Price', 'City', 'Site', 'Url'],
      dtype='object')

In [0]:
from bs4 import BeautifulSoup as BSHTML
import urllib
page = ureq('https://www.gaadi.com/usedcars/used-maruti-cars')
soup = BSHTML(page)
div1 = soup.findAll('div' , {"class" : "lst-heaing"})

In [0]:
liss = []
links = []
for i in range(len(div1)):
    #print(div1[i].text.split('\n')[1:-1] , div1[1].a['data-vdplink'])
    liss.append(div1[i].text.split('\n')[1:-1])
    links.append(div1[1].a['data-vdplink'])

In [0]:
liss1 = []
div1 = soup.findAll('div' , {"class" : "lst-dtl clearfix"})
for i in range(len(div1)):
    #print(div1[i].text.split('\n')[1:4])
    liss1.append(div1[i].text.split('\n')[1:4])

In [0]:
t = []
for i in range(len(liss)):
    t.append(liss[i]+liss1[i]+ [links[i]])

In [0]:
b = []
for i in range(len(liss)):
    b.append('Maruti Suzuki')
    
data1 = pd.DataFrame(t)  
data1.insert(1 , 'Brand' , b, True )

In [0]:
m=[]
k = list(data1[0].values)
for i in k:
    m.append(i.split()[1])
data1.insert(2 , 'Model' , m, True )

In [0]:
data1.insert(3 , 'Fuel Type' , list(data1[5].values), True )
data1.drop([5] , axis=1 , inplace=True)

In [0]:
data1.insert(4 , 'Model Year' , list(data1[3].values), True )
data1.drop([3] , axis=1 , inplace=True)

In [0]:
data1.insert(5 , 'Mileage' , list(data1[4].values), True )
data1.drop([4] , axis=1 , inplace=True)

In [0]:
data1.insert(6, 'Price' , list(data1[1].values), True )
data1.drop([1] , axis=1 , inplace=True)

In [0]:
data1.insert(7, 'City' , list(data1[2].values), True )
data1.drop([2] , axis=1 , inplace=True)

In [0]:
s=[]
k = list(data1[6].values)
for i in k:
    s.append(i.split('.')[1])
data1.insert(8, 'Site' , s, True )

In [0]:
data1.insert(9,  'Url' , list(data1[6].values), True )
data1.drop([6] , axis=1 , inplace=True)

In [0]:
v=[]
k = list(data1[0].values)
for i in k:
    v.append('+'.join(i.split()[2:]))
data1.insert(3,  'Variant' , v, True )

In [0]:
data1.insert(0,  'Car' , list(data1[0].values), True )
data1.drop([0] , axis=1 , inplace=True)

In [0]:
data1.head()

,Car,Brand,Model,Variant,Fuel Type,Model Year,Mileage,Price,City,Site,Url
0,Maruti Baleno 1.2 Delta,Maruti Suzuki,Baleno,1.2+Delta,Petrol,2016,"32,089 km",₹ 6.5 Lakh,"Bangalore City, Bangalore",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
1,Maruti Swift ZDi,Maruti Suzuki,Swift,ZDi,Diesel,2014,"39,918 km",₹ 5.9 Lakh,"Bangalore City, Bangalore",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
2,Maruti Baleno 1.2 Alpha,Maruti Suzuki,Baleno,1.2+Alpha,Petrol,2017,"6,000 km",₹ 7.65 Lakh,"Kandivali West, Mumbai",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
3,Maruti Celerio ZXI AT Optional,Maruti Suzuki,Celerio,ZXI+AT+Optional,Petrol,2017,"28,794 km",₹ 4.75 Lakh,"Baner, Pune",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
4,Maruti Ciaz 1.3 Alpha,Maruti Suzuki,Ciaz,1.3+Alpha,Diesel,2017,"28,274 km",₹ 8.7 Lakh,"Preet Vihar, New Delhi",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...

In [0]:

from bs4 import BeautifulSoup as BSHTML
import urllib
page = ureq('https://www.cartrade.com/buy-used-cars/gurgaon/maruti-suzuki/baleno/cmm')
soup = BSHTML(page)
div1 = soup.findAll('div' , {'class':'grid_cnt_new'})
#  'class' : 'grid_cnt_new'

In [0]:
import re
print(' '.join(div1[0].text.split()))
run = []
year = []
fuel = []
city=[]
car =[]
price =[]
b=[]
links=[]

for i in range(len(div1)):
    k = re.sub('\s+', ' ', div1[i].text).strip()
    car.append(k.split('₹')[0])
    price.append('₹ ' + k.split('₹')[1].split()[0])
    run.append(k.split('Price')[1].split('|')[0])
    fuel.append(k.split('Price')[1].split('|')[1])
    year.append(k.split('Price')[1].split('|')[3].split()[0])
    city.append(k.split('Price')[1].split('|')[3].split()[1])
    b.append('Maruti Suzuki')
    links.append('https://www.cartrade.com' + div1[i].a['href'])

Maruti Suzuki Baleno Delta 1.2 ₹ 5,80,000 Check Right Price 9,649 KMs | Petrol | 2 Owners | 2018 Gurgaon CONTACT SELLER More Cars from this Dealer

In [0]:
for i in range(len(city)):
    if(city[i]=='New'):
        city[i]='New Delhi'

In [0]:
m=[]
k = list(data2['Car'].values)
for i in k:
    m.append(i.split()[2])
    
v=[]
k = list(data2['Car'].values)
for i in k:
    v.append(i.split()[3])

In [0]:
s=[]
k = list(data2['Url'].values)
for i in k:
    s.append(i.split('.')[1])

In [0]:
data2 = pd.DataFrame()
data2['Car'] = car
data2['Brand'] = b

data2['Model'] = m
data2['Variant'] = v
data2['Fuel Type'] = fuel
data2['Model Year'] =year
data2['Mileage'] = run
data2['Price'] = price
data2['City'] = city
data2['Site'] =s
data2['Url'] = links
data2

,Car,Brand,Model,Variant,Fuel Type,Model Year,Mileage,Price,City,Site,Url
0,Maruti Suzuki Baleno Delta 1.2,Maruti Suzuki,Baleno,Delta,Petrol,2018,"9,649 KMs","₹ 5,80,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
1,Maruti Suzuki Baleno Delta ...,Maruti Suzuki,Baleno,Delta,Petrol,2017,"15,000 KMs","₹ 7,00,000",New Delhi,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
2,Maruti Suzuki Baleno Zeta D...,Maruti Suzuki,Baleno,Zeta,Diesel,2016,"45,000 KMs","₹ 7,25,000",New Delhi,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
3,Maruti Suzuki Baleno Delta ...,Maruti Suzuki,Baleno,Zeta,Petrol,2015,"45,000 KMs","₹ 4,95,000",New Delhi,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
4,Maruti Suzuki Baleno Zeta 1.2,Maruti Suzuki,Baleno,Delta,Petrol,2018,"22,900 KMs","₹ 7,00,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
5,Maruti Suzuki Baleno Sigma ...,Maruti Suzuki,Baleno,RS,Petrol,2017,"10,893 KMs","₹ 5,50,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
6,Maruti Suzuki Baleno Delta ...,Maruti Suzuki,Baleno,Delta,Petrol,2016,"20,551 KMs","₹ 5,50,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
7,Maruti Suzuki Baleno Zeta 1.2,Maruti Suzuki,Baleno,Alpha,Petrol,2018,"27,523 KMs","₹ 6,75,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
8,Maruti Suzuki Baleno Zeta 1.2,Maruti Suzuki,Baleno,Zeta,Petrol,2018,"27,523 KMs","₹ 6,75,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
9,Maruti Suzuki Baleno Delta ...,Maruti Suzuki,Baleno,Delta,Petrol,2017,"15,000 KMs","₹ 7,00,000",New Delhi,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
10,Maruti Suzuki Baleno Zeta A...,Maruti Suzuki,Baleno,Zeta,Petrol,2016,"23,991 KMs","₹ 6,35,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
11,Maruti Suzuki Baleno RS,Maruti Suzuki,Baleno,RS,Petrol,2017,"32,000 KMs","₹ 7,35,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
12,Maruti Suzuki Baleno Alpha ...,Maruti Suzuki,Baleno,Alpha,Diesel,2016,"22,664 KMs","₹ 7,50,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
13,Maruti Suzuki Baleno Zeta 1.2,Maruti Suzuki,Baleno,Zeta,Petrol,2018,"22,900 KMs","₹ 7,00,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
14,Maruti Suzuki Baleno Alpha ...,Maruti Suzuki,Baleno,Alpha,Petrol,2016,"23,051 KMs","₹ 6,75,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
15,Maruti Suzuki Baleno Delta ...,Maruti Suzuki,Baleno,Delta,Petrol,2016,"20,551 KMs","₹ 5,50,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
16,Maruti Suzuki Baleno Sigma ...,Maruti Suzuki,Baleno,Sigma,Petrol,2017,"10,893 KMs","₹ 5,50,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
17,Maruti Suzuki Baleno Zeta D...,Maruti Suzuki,Baleno,Zeta,Diesel,2016,"45,000 KMs","₹ 7,25,000",New Delhi,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
18,Maruti Suzuki Baleno Delta ...,Maruti Suzuki,Baleno,Delta,Petrol,2016,"32,230 KMs","₹ 5,40,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
19,Maruti Suzuki Baleno Delta 1.2,Maruti Suzuki,Baleno,Delta,Petrol,2018,"9,649 KMs","₹ 5,80,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
20,Maruti Suzuki Baleno Delta ...,Maruti Suzuki,Baleno,Delta,Petrol,2015,"45,000 KMs","₹ 4,95,000",New Delhi,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
21,Maruti Suzuki Baleno LXi,Maruti Suzuki,Baleno,LXi,Petrol,2004,"77,000 KMs","₹ 80,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
22,Maruti Suzuki Baleno Zeta P...,Maruti Suzuki,Baleno,Zeta,Petrol,2017,"18,000 KMs","₹ 7,50,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
23,Maruti Suzuki Baleno Alpha ...,Maruti Suzuki,Baleno,Alpha,Petrol,2016,"29,000 KMs","₹ 6,60,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
24,Maruti Suzuki Baleno Alpha ...,Maruti Suzuki,Baleno,Alpha,Diesel,2015,"16,000 KMs","₹ 6,75,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
25,Maruti Suzuki Baleno Alpha ...,Maruti Suzuki,Baleno,Alpha,Diesel,2015,"16,000 KMs","₹ 6,75,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...

In [0]:
data= pd.concat([data2, data1] , ignore_index = True)
data

,Car,Brand,Model,Variant,Fuel Type,Model Year,Mileage,Price,City,Site,Url
0,Maruti Suzuki Baleno Delta 1.2,Maruti Suzuki,Baleno,Delta,Petrol,2018,"9,649 KMs","₹ 5,80,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
1,Maruti Suzuki Baleno Delta ...,Maruti Suzuki,Baleno,Delta,Petrol,2017,"15,000 KMs","₹ 7,00,000",New Delhi,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
2,Maruti Suzuki Baleno Zeta D...,Maruti Suzuki,Baleno,Zeta,Diesel,2016,"45,000 KMs","₹ 7,25,000",New Delhi,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
3,Maruti Suzuki Baleno Delta ...,Maruti Suzuki,Baleno,Zeta,Petrol,2015,"45,000 KMs","₹ 4,95,000",New Delhi,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
4,Maruti Suzuki Baleno Zeta 1.2,Maruti Suzuki,Baleno,Delta,Petrol,2018,"22,900 KMs","₹ 7,00,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
5,Maruti Suzuki Baleno Sigma ...,Maruti Suzuki,Baleno,RS,Petrol,2017,"10,893 KMs","₹ 5,50,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
6,Maruti Suzuki Baleno Delta ...,Maruti Suzuki,Baleno,Delta,Petrol,2016,"20,551 KMs","₹ 5,50,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
7,Maruti Suzuki Baleno Zeta 1.2,Maruti Suzuki,Baleno,Alpha,Petrol,2018,"27,523 KMs","₹ 6,75,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
8,Maruti Suzuki Baleno Zeta 1.2,Maruti Suzuki,Baleno,Zeta,Petrol,2018,"27,523 KMs","₹ 6,75,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
9,Maruti Suzuki Baleno Delta ...,Maruti Suzuki,Baleno,Delta,Petrol,2017,"15,000 KMs","₹ 7,00,000",New Delhi,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
10,Maruti Suzuki Baleno Zeta A...,Maruti Suzuki,Baleno,Zeta,Petrol,2016,"23,991 KMs","₹ 6,35,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
11,Maruti Suzuki Baleno RS,Maruti Suzuki,Baleno,RS,Petrol,2017,"32,000 KMs","₹ 7,35,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
12,Maruti Suzuki Baleno Alpha ...,Maruti Suzuki,Baleno,Alpha,Diesel,2016,"22,664 KMs","₹ 7,50,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
13,Maruti Suzuki Baleno Zeta 1.2,Maruti Suzuki,Baleno,Zeta,Petrol,2018,"22,900 KMs","₹ 7,00,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
14,Maruti Suzuki Baleno Alpha ...,Maruti Suzuki,Baleno,Alpha,Petrol,2016,"23,051 KMs","₹ 6,75,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
15,Maruti Suzuki Baleno Delta ...,Maruti Suzuki,Baleno,Delta,Petrol,2016,"20,551 KMs","₹ 5,50,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
16,Maruti Suzuki Baleno Sigma ...,Maruti Suzuki,Baleno,Sigma,Petrol,2017,"10,893 KMs","₹ 5,50,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
17,Maruti Suzuki Baleno Zeta D...,Maruti Suzuki,Baleno,Zeta,Diesel,2016,"45,000 KMs","₹ 7,25,000",New Delhi,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
18,Maruti Suzuki Baleno Delta ...,Maruti Suzuki,Baleno,Delta,Petrol,2016,"32,230 KMs","₹ 5,40,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
19,Maruti Suzuki Baleno Delta 1.2,Maruti Suzuki,Baleno,Delta,Petrol,2018,"9,649 KMs","₹ 5,80,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
20,Maruti Suzuki Baleno Delta ...,Maruti Suzuki,Baleno,Delta,Petrol,2015,"45,000 KMs","₹ 4,95,000",New Delhi,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
21,Maruti Suzuki Baleno LXi,Maruti Suzuki,Baleno,LXi,Petrol,2004,"77,000 KMs","₹ 80,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
22,Maruti Suzuki Baleno Zeta P...,Maruti Suzuki,Baleno,Zeta,Petrol,2017,"18,000 KMs","₹ 7,50,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
23,Maruti Suzuki Baleno Alpha ...,Maruti Suzuki,Baleno,Alpha,Petrol,2016,"29,000 KMs","₹ 6,60,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
24,Maruti Suzuki Baleno Alpha ...,Maruti Suzuki,Baleno,Alpha,Diesel,2015,"16,000 KMs","₹ 6,75,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
25,Maruti Suzuki Baleno Alpha ...,Maruti Suzuki,Baleno,Alpha,Diesel,2015,"16,000 KMs","₹ 6,75,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
26,Maruti Baleno 1.2 Delta,Maruti Suzuki,Baleno,1.2+Delta,Petrol,2016,"32,089 km",₹ 6.5 Lakh,"Bangalore City, Bangalore",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
27,Maruti Swift ZDi,Maruti Suzuki,Swift,ZDi,Diesel,2014,"39,918 km",₹ 5.9 Lakh,"Bangalore City, Bangalore",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
28,Maruti Baleno 1.2 Alpha,Maruti Suzuki,Baleno,1.2+Alpha,Petrol,2017,"6,000 km",₹ 7.65 Lakh,"Kandivali West, Mumbai",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
29,Maruti Celerio ZXI AT Optional,Maruti Suzuki,Celerio,ZXI+AT+Optional,Petrol,2017,"28,794 km",₹ 4.75 Lakh,"Baner, Pune",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
30,Maruti Ciaz 1.3 Alpha,Maruti Suzuki,Ciaz,1.3+Alpha,Diesel,2017,"28,274 km",₹ 8.7 Lakh,"Preet Vihar, New Delhi",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
31,Maruti Dzire VXI,Maruti Suzuki,Dzire,VXI,Petrol,2014,"50,312 km",₹ 4.35 Lakh,"Virar E, Mumbai",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
32,Maruti SX4 Vxi BSIV,Maruti Suzuki,SX4,Vxi+BSIV,Petrol,2011,"67,000 km",₹ 2.35 Lakh,"Andheri, Mumbai",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
33,Maruti SX4 Zxi BSIII,Maruti Suzuki,SX4,Zxi+BSIII,Petrol,2009,"24,000 km",₹ 2.45 Lakh,"Andheri East, Mumbai",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
34,Maruti SX4 ZXI MT BSIV,Maruti Suzuki,SX4,ZXI+MT+BSIV,Petrol,2011,"60,000 km",₹ 2.75 Lakh,"Andheri West, Mumbai",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
35,Maruti Dzire ZXI,Maruti Suzuki,Dzire,ZXI,Petrol,2014,"23,377 km",₹ 5.3 Lakh,"Rajouri Garden, New Delhi",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
36,Maruti Ciaz ZXi,Maruti Suzuki,Ciaz,ZXi,Petrol,2015,"43,645 km",₹ 6.4 Lakh,"Virar E, Mumbai",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
37,Maruti Dzire VXI,Maruti Suzuki,Dzire,VXI,Petrol,2012,"39,559 km",₹ 4.15 Lakh,"Rajouri Garden, New Delhi",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...

In [0]:
# h = list(data['Fuel Type'].values)
# data.drop(['Fuel Type'] , axis=1 , inplace=True)
# data.insert(4, 'Fuel Type' , h, True )
# print(data.shape)
# data.head()

In [0]:
sn = []
for i in range(len(data)):
    sn.append(i+1)
data.insert(0, 'S.no' , sn,  True )
print(data.shape)
data.head()

(38, 12)

,S.no,Car,Brand,Model,Variant,Fuel Type,Model Year,Mileage,Price,City,Site,Url
0,1,Maruti Suzuki Baleno Delta 1.2,Maruti Suzuki,Baleno,Delta,Petrol,2018,"9,649 KMs","₹ 5,80,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
1,2,Maruti Suzuki Baleno Delta ...,Maruti Suzuki,Baleno,Delta,Petrol,2017,"15,000 KMs","₹ 7,00,000",New Delhi,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
2,3,Maruti Suzuki Baleno Zeta D...,Maruti Suzuki,Baleno,Zeta,Diesel,2016,"45,000 KMs","₹ 7,25,000",New Delhi,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
3,4,Maruti Suzuki Baleno Delta ...,Maruti Suzuki,Baleno,Zeta,Petrol,2015,"45,000 KMs","₹ 4,95,000",New Delhi,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
4,5,Maruti Suzuki Baleno Zeta 1.2,Maruti Suzuki,Baleno,Delta,Petrol,2018,"22,900 KMs","₹ 7,00,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...

In [0]:
k = list(data['Price'].values)
p=[]
for i in k:
    p.append(i.split('₹ ')[1])
data['Price'] =p

In [0]:
data

,S.no,Car,Brand,Model,Variant,Fuel Type,Model Year,Mileage,Price,City,Site,Url
0,1,Maruti Suzuki Baleno Delta 1.2,Maruti Suzuki,Baleno,Delta,Petrol,2018,"9,649 KMs","5,80,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
1,2,Maruti Suzuki Baleno Delta ...,Maruti Suzuki,Baleno,Delta,Petrol,2017,"15,000 KMs","7,00,000",New Delhi,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
2,3,Maruti Suzuki Baleno Zeta D...,Maruti Suzuki,Baleno,Zeta,Diesel,2016,"45,000 KMs","7,25,000",New Delhi,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
3,4,Maruti Suzuki Baleno Delta ...,Maruti Suzuki,Baleno,Zeta,Petrol,2015,"45,000 KMs","4,95,000",New Delhi,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
4,5,Maruti Suzuki Baleno Zeta 1.2,Maruti Suzuki,Baleno,Delta,Petrol,2018,"22,900 KMs","7,00,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
5,6,Maruti Suzuki Baleno Sigma ...,Maruti Suzuki,Baleno,RS,Petrol,2017,"10,893 KMs","5,50,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
6,7,Maruti Suzuki Baleno Delta ...,Maruti Suzuki,Baleno,Delta,Petrol,2016,"20,551 KMs","5,50,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
7,8,Maruti Suzuki Baleno Zeta 1.2,Maruti Suzuki,Baleno,Alpha,Petrol,2018,"27,523 KMs","6,75,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
8,9,Maruti Suzuki Baleno Zeta 1.2,Maruti Suzuki,Baleno,Zeta,Petrol,2018,"27,523 KMs","6,75,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
9,10,Maruti Suzuki Baleno Delta ...,Maruti Suzuki,Baleno,Delta,Petrol,2017,"15,000 KMs","7,00,000",New Delhi,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
10,11,Maruti Suzuki Baleno Zeta A...,Maruti Suzuki,Baleno,Zeta,Petrol,2016,"23,991 KMs","6,35,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
11,12,Maruti Suzuki Baleno RS,Maruti Suzuki,Baleno,RS,Petrol,2017,"32,000 KMs","7,35,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
12,13,Maruti Suzuki Baleno Alpha ...,Maruti Suzuki,Baleno,Alpha,Diesel,2016,"22,664 KMs","7,50,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
13,14,Maruti Suzuki Baleno Zeta 1.2,Maruti Suzuki,Baleno,Zeta,Petrol,2018,"22,900 KMs","7,00,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
14,15,Maruti Suzuki Baleno Alpha ...,Maruti Suzuki,Baleno,Alpha,Petrol,2016,"23,051 KMs","6,75,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
15,16,Maruti Suzuki Baleno Delta ...,Maruti Suzuki,Baleno,Delta,Petrol,2016,"20,551 KMs","5,50,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
16,17,Maruti Suzuki Baleno Sigma ...,Maruti Suzuki,Baleno,Sigma,Petrol,2017,"10,893 KMs","5,50,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
17,18,Maruti Suzuki Baleno Zeta D...,Maruti Suzuki,Baleno,Zeta,Diesel,2016,"45,000 KMs","7,25,000",New Delhi,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
18,19,Maruti Suzuki Baleno Delta ...,Maruti Suzuki,Baleno,Delta,Petrol,2016,"32,230 KMs","5,40,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
19,20,Maruti Suzuki Baleno Delta 1.2,Maruti Suzuki,Baleno,Delta,Petrol,2018,"9,649 KMs","5,80,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
20,21,Maruti Suzuki Baleno Delta ...,Maruti Suzuki,Baleno,Delta,Petrol,2015,"45,000 KMs","4,95,000",New Delhi,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
21,22,Maruti Suzuki Baleno LXi,Maruti Suzuki,Baleno,LXi,Petrol,2004,"77,000 KMs","80,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
22,23,Maruti Suzuki Baleno Zeta P...,Maruti Suzuki,Baleno,Zeta,Petrol,2017,"18,000 KMs","7,50,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
23,24,Maruti Suzuki Baleno Alpha ...,Maruti Suzuki,Baleno,Alpha,Petrol,2016,"29,000 KMs","6,60,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
24,25,Maruti Suzuki Baleno Alpha ...,Maruti Suzuki,Baleno,Alpha,Diesel,2015,"16,000 KMs","6,75,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
25,26,Maruti Suzuki Baleno Alpha ...,Maruti Suzuki,Baleno,Alpha,Diesel,2015,"16,000 KMs","6,75,000",Gurgaon,cartrade,https://www.cartrade.com/buy-used-cars/gurgaon...
26,27,Maruti Baleno 1.2 Delta,Maruti Suzuki,Baleno,1.2+Delta,Petrol,2016,"32,089 km",6.5 Lakh,"Bangalore City, Bangalore",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
27,28,Maruti Swift ZDi,Maruti Suzuki,Swift,ZDi,Diesel,2014,"39,918 km",5.9 Lakh,"Bangalore City, Bangalore",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
28,29,Maruti Baleno 1.2 Alpha,Maruti Suzuki,Baleno,1.2+Alpha,Petrol,2017,"6,000 km",7.65 Lakh,"Kandivali West, Mumbai",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
29,30,Maruti Celerio ZXI AT Optional,Maruti Suzuki,Celerio,ZXI+AT+Optional,Petrol,2017,"28,794 km",4.75 Lakh,"Baner, Pune",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
30,31,Maruti Ciaz 1.3 Alpha,Maruti Suzuki,Ciaz,1.3+Alpha,Diesel,2017,"28,274 km",8.7 Lakh,"Preet Vihar, New Delhi",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
31,32,Maruti Dzire VXI,Maruti Suzuki,Dzire,VXI,Petrol,2014,"50,312 km",4.35 Lakh,"Virar E, Mumbai",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
32,33,Maruti SX4 Vxi BSIV,Maruti Suzuki,SX4,Vxi+BSIV,Petrol,2011,"67,000 km",2.35 Lakh,"Andheri, Mumbai",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
33,34,Maruti SX4 Zxi BSIII,Maruti Suzuki,SX4,Zxi+BSIII,Petrol,2009,"24,000 km",2.45 Lakh,"Andheri East, Mumbai",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
34,35,Maruti SX4 ZXI MT BSIV,Maruti Suzuki,SX4,ZXI+MT+BSIV,Petrol,2011,"60,000 km",2.75 Lakh,"Andheri West, Mumbai",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
35,36,Maruti Dzire ZXI,Maruti Suzuki,Dzire,ZXI,Petrol,2014,"23,377 km",5.3 Lakh,"Rajouri Garden, New Delhi",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
36,37,Maruti Ciaz ZXi,Maruti Suzuki,Ciaz,ZXi,Petrol,2015,"43,645 km",6.4 Lakh,"Virar E, Mumbai",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...
37,38,Maruti Dzire VXI,Maruti Suzuki,Dzire,VXI,Petrol,2012,"39,559 km",4.15 Lakh,"Rajouri Garden, New Delhi",gaadi,https://www.gaadi.com/usedcars/details-0c844e4...

In [0]:
data.set_index('S.no' , inplace = True)
data.to_csv('Used_Car_Data.csv' , index =True)

In [0]:

# from bs4 import BeautifulSoup as BSHTML
# import urllib
# page = ureq('https://droom.in/cars/used?page=1&tab=grid&bucket=car&category=car&condition=used&make=ford')
# soup = BSHTML(page)
# div1 = soup.findAll('div' , {'class' : 'details'})


# pag = requests.get('https://droom.in/cars/used?page=1&tab=grid&bucket=car&category=car&condition=used&make=ford')
# doc = lh.fromstring(pag.content)
# #Parse data that are stored between <tr>..</tr> of HTML
# tr_elements = doc.xpath('//a')
# # for i in range(len(tr_elements)):
# #     print(tr_elements[i].text_content().strip()[-15])

# for i in range(2,len(div1)):
#     l = div1[i].text.split('\n')
#     n=[]
#     for j in l:
#         if(len(j)>1):
#             n.append(j)

#     print(n[5:10])